### ISSUE TITLE
run() is not a function

### ISSUE THREAD

**Issue by justapieop** [shitcorp/discord-bot-dashboard#104]
Hi, when i tried to use the run function, it showed the above error. please help, thanks

**Comment by Huskydog9988** [comment]
Well, the current version of the dashboard has `run` as a method of the `Dashboard` class. Please see the file [here](https://github.com/julianYaman/discord-bot-dashboard/blob/master/test.js) for an example of the dashboard. 

-

**Comment by JustAPieOP** [comment]
Well, as I was following the implementation example, the error is shown that the run() function isn't accessible

**Comment by Huskydog9988** [comment]
You are aware that this isn’t a published npm package yet right?

**Comment by Huskydog9988** [comment]
The project has comepletly changed its codease and this is no longer valid.
