### ISSUE TITLE
Eris (+ adding screenshots to the README)

### ISSUE THREAD

**Issue by Hector6704** [shitcorp/discord-bot-dashboard#43]
can this dahsboard works for eris bots ? 
Also you should put screenshots of the dashboard in the readme

**Comment by julianYaman** [comment]
Putting screenshots will be one task to be done.
It is not planned to make the dashboard compatible for bots using Eris.

Currently the dashboard gets recoded. If you want, you can contribute to the recoding and to the discussion ( #83 ).

**Comment by Huskydog9988** [comment]
I may add Eris support as I use it some of the time, and if I do that will take a while to complete due to the complex nature of Eris.

**Comment by Huskydog9988** [comment]
The project has comepletly changed its codease and this is no longer valid.
