### ISSUE TITLE
Writing a documentation

### ISSUE THREAD

**Issue by julianYaman** [shitcorp/discord-bot-dashboard#87]
A documentation would help contributors and bot developers who want to use the dashbaord to know how to use it correctly.

It also helps to troubleshoot problems easier.

**Comment by julianYaman** [comment]
Documentation will be in the „Wiki“ section of this GitHub Repository and eventually on an extra web page.

**Comment by WickedWizard3588** [comment]
Hey,
I could write the Docs, if you're ok, but I need some help with the Dashboard right now, after I know it properly, I can write it :)

That is if, you're ok 😉

**Comment by Huskydog9988** [comment]
The project has comepletly changed its codease and this is no longer valid.
