### ISSUE TITLE
Adding control functions for the dashboard

### ISSUE THREAD

**Issue by julianYaman** [shitcorp/discord-bot-dashboard#88]
**Is your feature request related to a problem? Please describe.**
The dashboard needs the functionality to control the bot directly.

**Describe the solution you'd like**
- [ ] Changing the game status of the bot
- [ ] Changing the status of the bot
- [ ] Changing the config file (e.g. version, etc. - concept need to be worked out)

**Comment by ToledoSDL** [comment]
@julianYaman i will make this 💯

**Comment by Huskydog9988** [comment]
The project has comepletly changed its codease and this is no longer valid.
